/**
 * Compatibility fixtures for the rename lane (plan Task 3 Step 3): the corpus's readers keep reading today's stored
 * shapes unchanged. The fixtures under rename/fixtures/ are copies of today's weave and loom manifests and of a strand's
 * frontmatter shape (with its own id, slug and title, so the validator's duplicate check never sees one id twice).
 * The `relationships:` key and the stored values stay as they are (spec 6.2).
 *
 * Run: npx vitest run tests/rename-fixtures.test.js
 */

import { describe, it, expect } from 'vitest';

const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');
const yaml = require('js-yaml');
const CodexValidator = require('../scripts/validate.js');
const { CodexIndexer } = require('../scripts/auto-index.js');

const fixtures = path.join(__dirname, '..', 'rename', 'fixtures');
const weavePath = path.join(fixtures, 'weaves', 'wiki', 'weave.yaml');
const loomPath = path.join(fixtures, 'weaves', 'wiki', 'frame', 'loom.yaml');
const strandPath = path.join(fixtures, 'weaves', 'wiki', 'architecture', 'overview.md');
const STRAND_KEYS = ['id', 'slug', 'title', 'summary', 'version', 'contentType', 'difficulty', 'taxonomy', 'tags', 'relationships', 'publishing', 'blocks'];
const REFERENCES = ['sql-cache-architecture', 'nlp-pipeline', 'automation-workflows'];

describe("rename fixtures: the corpus readers keep today's shapes", () => {
  it('reads the weave manifest unchanged', () => {
    const weave = yaml.load(fs.readFileSync(weavePath, 'utf8'));
    expect(weave.slug).toBe('wiki');
    expect(weave.looms).toEqual(['frame', 'openstrand', 'architecture', 'contributing', 'development', 'examples', 'tutorials']);
    expect(weave.publishing).toEqual({ status: 'published', maintainers: ['jddunn'] });
    const validator = new CodexValidator();
    expect(validator.validateFile(weavePath)).toBe(true);
    expect(validator.errors).toEqual([]);
  });

  it('reads the loom manifest unchanged', () => {
    const loom = yaml.load(fs.readFileSync(loomPath, 'utf8'));
    expect(loom.slug).toBe('frame');
    expect(loom.ordering).toBe('manual');
    expect(loom.relationships).toEqual([
      { targetSlug: 'openstrand', type: 'extends', strength: 0.8 },
      { targetSlug: 'architecture', type: 'parallels', strength: 0.7 },
    ]);
    const validator = new CodexValidator();
    expect(validator.validateFile(loomPath)).toBe(true);
    // validateLoom rejects `ordering: manual` today, and both corpus looms carry it; no other error may appear.
    expect(validator.errors.filter((e) => !/ordering/i.test(e))).toEqual([]);
  });

  it('reads the strand frontmatter unchanged and round-trips it', () => {
    const raw = fs.readFileSync(strandPath, 'utf8');
    const { data, content } = matter(raw);
    expect(Object.keys(data)).toEqual(STRAND_KEYS);
    expect(data.relationships).toEqual({ references: REFERENCES });
    expect(data.taxonomy).toEqual({ subjects: ['technology', 'knowledge'], topics: ['architecture', 'getting-started'] });
    expect(data.publishing).toEqual({ status: 'published' });
    expect(data.blocks[0]).toMatchObject({ type: 'heading', headingLevel: 1, line: 2 });
    const again = matter(matter.stringify(content, data));
    expect(again.data).toEqual(data);
    expect(again.content.trim()).toBe(content.trim());
  });

  it('validates and indexes the strand as today', () => {
    const validator = new CodexValidator();
    expect(validator.validateFile(strandPath)).toBe(true);
    expect(validator.errors).toEqual([]);
    const indexer = new CodexIndexer();
    const entry = indexer.processFile(strandPath, fixtures);
    expect(indexer.stats.errors).toEqual([]);
    expect(entry).not.toBeNull();
    expect(entry.path).toBe('weaves/wiki/architecture/overview.md');
    expect(entry.metadata.id).toBe('3fce914f-0801-45fd-b886-f0521aeeb4a1');
    expect(entry.metadata.relationships).toEqual({ references: REFERENCES });
    expect(entry.metadata.autoGenerated).toBeDefined();
  });
});
